### ISSUE TITLE
Finland and Romenia flags emoji typo

### ISSUE THREAD

**Issue by JuniorJairo** [learn-english-community/learn-english-bot#38]
## Bug description
On the Languages.java file the Finland and Romania flags emoji have a typo, therefore not displaying the actual flags on text channels.

## Steps to reproduce
  1. Using the slash command, type `/translate`;
  2. Select any text as first argument;
  3. Choose the Finnish language as second argument;
  4. Reproduce above steps with Romenia.

## Expected behavior
It should be showing Finnland and Romenia flags emoji, instead it shows simply a string.

**Comment by christolis** [comment]
Nice catch! Do you want to work on this @JuniorJairo? 🤔

**Comment by JuniorJairo** [comment]
Oh yeah! it's a minor fix so I'll take of it myself don't worry
Also, if you catch more of these minor issues just DM me on Discord and I'll take care of them.
